### ISSUE TITLE
Question About TechReport

### ISSUE THREAD

**Issue by JackKaiXing** [SmallVCM/SmallVCM#10]
Hello,

In the report "Implementing Vertex Connection and Merging", for equation 11 on page 3,
<img width="381" alt="equation11" src="https://user-images.githubusercontent.com/21079351/155348129-0b7830fe-5f25-48be-825a-0ceefe646465.png">
for different X<sub>l</sub>, what does s>=0 and k>=0 mean?

The given path, X<sub>l</sub>, to my understand, has only one sampled s/t combination, would not have all kinds of s/t combinations, like 0/0, 0/1, 1/0,2/0,2/1.....Why do we need to accumulate for all s/t combinations?

Any misunderstanding here?

**Comment by JackKaiXing** [comment]
Does it mean, for vertex connection, each vertex of an eye sub-path and each vertex of a light sub-path, could be connected to form a potential path?

**Comment by iliyang** [comment]
Hey, the notation is probably not ideal here, I admit. The first term in the equation considers a single camera subpath and `n_vc` light subpaths; this is the outer sum. For each light subpath `l`, the inner sum considers _full_ paths, each constructed by connecting the `s`-th light-subpath vertex to the `t`-th camera-subpath vertex. In theory, this inner sum is infinite, but due to Russian roulette termination applied to the sampling of these subpaths in practice it is finite. Note that this inner sum is the same as the one in classical bidirectional path tracing (see Veach's thesis, eq. 10.3 on page 300), the only difference being that the MIS weight in our case also considers merging techniques. Hope this helps.

**Comment by JackKaiXing** [comment]
Thanks a lot. It helps.

**Comment by JackKaiXing** [comment]
@iliyang 

Hi there, 

I am currently reading through your paper. It is a little bit hard for me to fully understand, since I am new to this field. Could you please explain more on `equation 12`, about which I got several other questions as follows. 

- Does the `n_vc` and `n_vm` is the same as equation 11,? If not, what are they really means?
- The sum for `s'` and `t'`, is it related to `all` the potential full paths generated by the camera path and the current light subpath `l`? As the weight function of Veach's thesis on page 305, the weight function depends on all the paths of the same length k, as I understand.
- In the denominator, it has both VC and VM. Does it mean that the current light subpath `l` is both used for VC and VM with camera path?

**Comment by iliyang** [comment]
If you're new to the field, and specifically to multiple importance sampling (MIS) and bidirectional path tracing (BPT), it may be better to familiarize yourself better with these two, because VCM is another layer on top of these.

Regarding your questions:
-  `n_vc` and `n_vm` are indeed the same as in eq.11. Note that in eq.12, `v` can be either `VC` or `VM`, so `w_{v,s,t}` is a common form for the weights in eq.12.
- No, eq.12 computes the MIS weight for a given path, which involves evaluating the PDFs of all techniques that could generate that path. The `s'` and `t'` sums iterate over those techniques.
- Any given path can be generated by multiple VC techniques and multiple VM techniques. The nominator iterates over all of them.

I agree that eq.12 can be difficult to wrap your head around. But it is simply an extension to the MIS weight of BPT that considers a larger set of techniques. So you may want to first read more about BPT to become more comfortable with it, then come back to VCM.

**Comment by JackKaiXing** [comment]
@iliyang 

Thanks for reply and your advice.

Besides, could you please explain more on `p_0_connect` and `p_0_trace`, eq.31. What does it mean, "whether it will be connected to a sub-path or used to start a new sub-path. "?

Is the `directPdfA`, in the below line, to be `p_0_connect`?
https://github.com/SmallVCM/SmallVCM/blob/a13690f03d3414f76ba32b5f0e259e6e5d10ed7b/src/vertexcm.hxx#L844

**Comment by iliyang** [comment]
`p_0^conect` is the pdf for sampling the vertex on the light source using a direct lighting strategy, and `p_0^trace` is the pdf for the same vertex when sampled as the first vertex of a light path. And yes, `directPdfA` is indeed `p_0^connect` in the source line you referenced above.

**Comment by JackKaiXing** [comment]
Thanks for reply. 

For the `p_0^trace`, inside `GenerateLightSample` function, I do not see it anywhere, then I suppose it to 1. Right? When would this value not equal to 1? Since the vertex is in the light source, it would be the first one of a light path.  I believe, there must be something that I do not understand.

https://github.com/SmallVCM/SmallVCM/blob/a13690f03d3414f76ba32b5f0e259e6e5d10ed7b/src/vertexcm.hxx#L816

**Comment by iliyang** [comment]
The code uses `emissionPdfW` to denote `p_0^trace`, and it does appeat in the `GenerateLightSample()` function — there's even a code comment in side the function mentioning that eqs.31-33 are being implemented. Note this in the aforementioned expression `directPdfA / emissionPdfW` which corresponds to (the first part of) eq.31.

**Comment by JackKaiXing** [comment]
Great Thanks.

I must mistake `emissionPdfW` as `p_1^->` of eq.31. Sorry for that. But I am more confused about `p_1^->` of eq.31. Based on eq.2.3.4, `p_1^->`(the forward pdf) should have three parts.

I can find the cosine term here.
https://github.com/SmallVCM/SmallVCM/blob/a13690f03d3414f76ba32b5f0e259e6e5d10ed7b/src/vertexcm.hxx#L357.

**Comment by iliyang** [comment]
Ah, sorry, it's my fault — I got it wrong. I think `emissionPdfW` is actually the solid-angle pdf for sampling the emission direction, which is indeed part of `p_1`. The code ignores the `p_0^connect / p_0^trace` term in eq.31 because these two pdfs are identical in this implementation and cancel out — points on light sources are always sampled with the same pdf whether it's for emission or for connection.

**Comment by JackKaiXing** [comment]
@iliyang 
Thanks a lot.
