### ISSUE TITLE
Conversion of weights to area pdf during path tracing

### ISSUE THREAD

**Issue by mgamito** [SmallVCM/SmallVCM#7]
This is not really an issue but a request for explanation. I'm not understanding this part of the code in camera tracing:

    // Update the MIS quantities, following the initialization in
    // GenerateLightSample() or SampleScattering(). Implement equations
    // [tech. rep. (31)-(33)] or [tech. rep. (34)-(36)], respectively.
    {
        cameraState.dVCM *= Mis(Sqr(isect.dist));
        cameraState.dVCM /= Mis(std::abs(bsdf.CosThetaFix()));
        cameraState.dVC  /= Mis(std::abs(bsdf.CosThetaFix()));
        cameraState.dVM  /= Mis(std::abs(bsdf.CosThetaFix()));
    }

All three VCM weights require an area pdf as denominator in eqs. (34)-(36). Conversion to area measure requires multiplication of the weights by squared distance and division by cosine. Why is it that only dVCM is multiplied by the squared distance? A similar thing happens during light tracing.

Thanks.

**Comment by iliyang** [comment]
Sorry for the late reply, Manuel. This part was implemented by Tomas, so I hope he can give a better answer. But as far as I remember, this is just an implementation optimization which omits terms that will cancel out anyway. Specifically, `dVC` and `dVM` are not multiplied by the squared distance because it cancels out with the same squared distance that appears in the `g_{i-1}` term in the nominator in (35) and (36).

**Comment by tomas-davidovic** [comment]
Hi, it is pretty much exactly what Iliyan said. When we wrote this, we've debated quite a bit between making it 1:1 copy the equations (as they were at the time) and making it not completely stupid. The code ended-up somewhere in-between, so the most obvious cancellations are baked in already.

**Comment by mgamito** [comment]
Great, I understand. Thanks for the explanation!
